export const SET_QUERY = "SEARCH_SET_QUERY";
export const SET_SHOWFLAG = "SEARCH_SET_SHOWFLAG";
export const SET_RESULT = "SEARCH_SET_RESULT";
export const SET_SEARCHHISTORY = "SEARCH_SET_SEARCHHISTORY";
export const SET_GOTOSINGER = "SEARCH_SET_GOTOSINGER";
export const SET_ISSEARCHING = "SEARCH_SET_ISSEARCHING";
export const TYPE_SINGER = "singer";
export const TYPE_SONG = "song";
