export const playMode = {
  sequence: 0,
  loop: 1,
  random: 2,
};

export const SET_SINGER = "PLAYER_SET_SINGER";
export const SET_PLAYING = "PLAYER_SET_PLAYING";
export const SET_FULLSCREEN = "PLAYER_SET_FULLSCREEN";
export const SET_PLAYLIST = "PLAYER_SET_PLAYLIST";
export const SET_SEQUENCELIST = "PLAYER_SET_SEQUENCELIST";
export const SET_MODE = "PLAYER_SET_MODE";
export const SET_CURRENTINDEX = "PLAYER_SET_CURRENTINDEX";
export const SET_CURRENTSONG = "PLAYER_SET_CURRENTSONG";
export const SET_PLAYINGLYRIC = "PLAYER_SET_PLAYINGLYRIC";
export const SET_CURRENTLINENUM = "PLAYER_SET_CURRENTLINENUM";
export const SET_CURRENTLYRIC = "PLAYER_SET_CURRENTLYRIC";
export const SET_CURRENTTIME = "PLAYER_SET_CURRENTTIME";
export const SET_SHOWPLAYLIST = "PLAYER_SET_SHOWPLAYLIST";
export const SET_SONGREADY = "PLAYER_SET_SONGREADY";
export const SET_NEWTIME = "PLAYER_SET_NEWTIME";
export const SET_CURRENTOFFSET = "PLAYER_SET_CURRENTOFFSET";
