export const SET_BANNERLIST = "RECOMMEND_SET_BANNERLIST";
export const SET_RECOMMENDLIST = "RECOMMEND_SET_RECOMMENDLIST";
export const SET_ENTERLOADING = "RECOMMEND_SET_ENTERLOADING";
export const SET_PULLDOWNLOADING = "RECOMMEND_SET_PULLDOWNLOADING";
