export const SET_BANNERLIST = "SET_BANNERLIST";
export const SET_RECOMMENDLIST = "SET_RECOMMENDLIST";
export const SET_ENTERLOADING = "SET_ENTERLOADING";
export const SET_PULLDOWNLOADING = "SET_PULLDOWNLOADING";
